export const {
  VITE_HOMEPAGE_URL: HOMEPAGE_URL,
  VITE_APP_URL: APP_URL,
  VITE_AUTHORIZATION_URL: AUTHORIZATION_URL,
  VITE_API_URL: API_URL,
  VITE_JWKS_URL: JWKS_URL,
  VITE_OAUTH_CLIENT_ID: OAUTH_CLIENT_ID
} = import.meta.env;
